### ISSUE TITLE
Vite-ssg build error in SSR step

### ISSUE THREAD

**Issue by ademtonay** [antfu-collective/vite-ssg#404]
### Describe the bug

I'm using [vue3-carousel](https://www.npmjs.com/package/vue3-carousel) in my project and getting following error while building with `build` script.

```less
[vite-ssg] Build for server...
vite v5.2.11 building SSR bundle for production...
Ambiguous external namespace resolution: "virtual:vue-router/auto" re-exports "useRouter" from one of the external modules "vue-router" and "unplugin-vue-router/data-loaders/basic", guessing "vue-router".
"useRouter" is imported from external module "unplugin-vue-router/data-loaders/basic" but never used in "virtual:vue-router/auto".
✓ 66 modules transformed.
✓ 0 webfont css downloaded. (0 ms, cache hit: NaN%)
.vite-ssg-temp/7un0o79hrz/manifest.webmanifest                         0.39 kB
.vite-ssg-temp/7un0o79hrz/assets/style-EG92fjKA.css                   35.60 kB
.vite-ssg-temp/7un0o79hrz/assets/route-block-mFfs_uHM.js               0.05 kB
.vite-ssg-temp/7un0o79hrz/assets/en-DrlAedJ-.js                        1.14 kB
.vite-ssg-temp/7un0o79hrz/assets/tr-BgRAO5hH.js                        1.16 kB
.vite-ssg-temp/7un0o79hrz/assets/_...all_-Emgd7hKA.js                  1.19 kB
.vite-ssg-temp/7un0o79hrz/assets/virtual_pwa-register-MFElTJ3Z.js      1.45 kB
.vite-ssg-temp/7un0o79hrz/assets/workbox-window.prod.es5-BZWEBaKl.js   8.18 kB
.vite-ssg-temp/7un0o79hrz/assets/index-BkKP3A0x.js                    43.61 kB
.vite-ssg-temp/7un0o79hrz/main.mjs                                    78.91 kB
✓ built in 452ms
file:///Users/ademtonay/Projects/kt-dent/.vite-ssg-temp/7un0o79hrz/assets/index-BkKP3A0x.js:4
import { Carousel, Navigation, Pagination, Slide } from "vue3-carousel";
         ^^^^^^^^
SyntaxError: The requested module 'vue3-carousel' does not provide an export named 'Carousel'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/ademtonay/Projects/kt-dent/.vite-ssg-temp/7un0o79hrz/assets/index-BkKP3A0x.js:4
import { Carousel, Navigation, Pagination, Slide } from "vue3-carousel";
         ^^^^^^^^
SyntaxError: The requested module 'vue3-carousel' does not provide an export named 'Carousel'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)

Node.js v20.13.1
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

none

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 619.52 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    npm: 10.2.5 - /usr/local/bin/npm
    pnpm: 9.1.1 - ~/Projects/kt-dent/node_modules/.bin/pnpm
  Browsers:
    Chrome: 124.0.6367.209
    Safari: 17.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)
